### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by smartvdo** [zhangqianhui/CnnForAndroid#1]
Hi, qianhui,

Firstly thank you for contribute this project. 
I am a newbie of Android, and I am trying to following your instruction to build the tiny-cnn. After running the ndk-build under the fold "jni", I ony see the libcaffe_p.so is generated successfully. why is there no other lib and executable files?  
I read the jni/Android.mk, It shows:
# 

LOCAL_PATH := $(call my-dir)  

include $(CLEAR_VARS)  
OpenCV_INSTALL_MODULES:=on
OPENCV_CAMERA_MODULES:=off
OPENCV_LIB_TYPE:=SHARE
LOCAL_CPP_EXTENSION := .cc
include D:\OpenCV-3.0.0-android-sdk-1\OpenCV-android-sdk\sdk\native\jni\OpenCV.mk

LOCAL_MODULE  := caffe_p
LOCAL_SRC_FILES  := cnnInterface.cpp , caffe.pb.cc , common.cpp
LOCAL_LDLIBS += -lm -llog 
# 指定头文件路径
# LOCAL_C_INCLUDES = $(LOCAL_PATH)/src
# 指定静态库

LOCAL_LDFLAGS += $(LOCAL_PATH)/libprotobuf.a

include $(BUILD_SHARED_LIBRARY)
# 

No other "LOCAL_MODULE" necessarily to be compiled?

Thanks.

**Comment by zhangqianhui** [comment]
static lib?

**Comment by smartvdo** [comment]
For example, 
1. how is tiny-cnn compiled to .so ?
2. how to run your vehicle recognition example ? ( I am not able to find the jni\test.cpp in the release.

**Comment by zhangqianhui** [comment]
How to run? You can use the eclipse tool  to install in your phone and test it!

**Comment by smartvdo** [comment]
Hi, qianhui, Thanks. 
I just want to know where the vehicle recognition example is located in your release and how to compile it into the android executable?

**Comment by zhangqianhui** [comment]
You can download it , for example git clone "address" and install adt-bundle eclipse , then use it to open project , finish compile !
